// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS64ni7MOd8_WbjIH1nRaYN61GYYX0Gkg',
    appId: '1:984086906910:web:2ca5f04d1d777be747460f',
    messagingSenderId: '984086906910',
    projectId: 'digichat-flutter',
    authDomain: 'digichat-flutter.firebaseapp.com',
    storageBucket: 'digichat-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9pkpfZqJHJdd_ITZAFvBsoOmcwQKB9_w',
    appId: '1:984086906910:android:5158f9edaf25b23c47460f',
    messagingSenderId: '984086906910',
    projectId: 'digichat-flutter',
    storageBucket: 'digichat-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6J5r3SDFZ56nLsnZ9m7eYvTX2xIs9qU',
    appId: '1:984086906910:ios:de2b4749208d922947460f',
    messagingSenderId: '984086906910',
    projectId: 'digichat-flutter',
    storageBucket: 'digichat-flutter.appspot.com',
    iosClientId: '984086906910-2f5jja1r3puod0od1c40oteg59k1flv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.digichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6J5r3SDFZ56nLsnZ9m7eYvTX2xIs9qU',
    appId: '1:984086906910:ios:de2b4749208d922947460f',
    messagingSenderId: '984086906910',
    projectId: 'digichat-flutter',
    storageBucket: 'digichat-flutter.appspot.com',
    iosClientId: '984086906910-2f5jja1r3puod0od1c40oteg59k1flv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.digichat',
  );
}
